import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

import { backend, mediaFolder, publicFolder, siteUrl, slug } from './base.js';
import { settingsCollection } from './collections/settings.js';
import { anunciosCollection } from './collections/anuncios.js';
import { circularesCollection } from './collections/circulares.js';
import { capacitacionesCollection } from './collections/capacitaciones.js';
import { eventosCollection } from './collections/eventos.js';
import { enlacesCollection } from './collections/enlaces.js';
import { directorioCollection } from './collections/directorio.js';
import { documentosCollection } from './collections/documentos.js';
import { bienestarCollection } from './collections/bienestar.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, '../public/admin/config.yml');

const config = {
  backend,
  media_folder: mediaFolder,
  public_folder: publicFolder,
  site_url: siteUrl,
  slug,
  collections: [
    settingsCollection,
    anunciosCollection,
    circularesCollection,
    capacitacionesCollection,
    eventosCollection,
    enlacesCollection,
    directorioCollection,
    documentosCollection,
    bienestarCollection,
  ],
};

const yamlStr = yaml.dump(config, {
  lineWidth: 120,
  noRefs: false,
  quotingType: '"',
  forceQuotes: false,
});

const header = '# AUTO-GENERATED by cms/generate.js — DO NOT EDIT MANUALLY\n\n';

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, header + yamlStr, 'utf-8');

console.log(`[CMS] config.yml generated → ${OUTPUT}`);
